Multi-arch support
divnix/devos pull request #161
Opened 2021-03-14 20:15 UTC by Pacman99

This allows users to set `nixpkgs.system` to any architecture exported by the nixpkgs flake and nixpkgs.pkgs will be set to that system.

I also added `multiPkgs` as a special arg and make `nixpkgs.pkgs` a default. So if someone wanted to do crossSystem builds or anything else with pkgs, that is also an option(eg. mobile-nixos!!).

2021-03-14 20:30 UTC, Pacman99 commented on hosts/NixOS-a64.nix
> +  nixpkgs.system = "aarch64-linux";
This entire file is probably unnecessary and I could just add that line to the hosts README. But it is nice for testing the PR.

2021-03-14 20:49 UTC, Pacman99 commented on lib/default.nix
> -args@{ nixos, pkgs, ... }:
I don't think lib functions should ever need to depend on pkgs. I think nixos.lib should be enough.

2021-03-14 23:06 UTC, nrdxp requested changes

2021-03-14 23:06 UTC, nrdxp commented on hosts/default.nix
> +    inherit suites multiPkgs;
Do we need `multiPkgs` as a specialArg? When would one system ever need access to anothers package set? Are you thinking for cross compiling?

2021-03-14 23:06 UTC, nrdxp commented on lib/default.nix
> -args@{ nixos, pkgs, ... }:
agreed, @blaggacao, you added this. Could you explain why it was added and if it's okay to remove from your point of view? Also, I believe the [docs on lib](https://devos.divnix.com/lib/index.html) need to be updated regardless.

2021-03-14 23:14 UTC, Pacman99 commented on hosts/default.nix
> +    inherit suites multiPkgs;
Yeah exactly, I was specifically thinking cross compiling. Since you can no longer set localSystem and crossSystem in a devos host. But I'm not sure if its needed either, idk much about cross compiling.

2021-03-14 23:17 UTC, nrdxp commented on hosts/NixOS-a64.nix
> +  nixpkgs.system = "aarch64-linux";
Instead of this file, I would write a NixOS integration test similar to the [profilesTest](https://github.com/divnix/devos/blob/core/tests/default.nix#L63-L73)

2021-03-14 23:28 UTC, nrdxp commented on hosts/default.nix
> +    inherit suites multiPkgs;
So one can already build cross packages for a given platform from the `pkgsCross` meta package. However, maybe this could still be useful. 

One should be able to build these `multiPkgs` with the proper binfmt registered though. For example, on the hercules-ci runner i have set: `boot.binfmt.emulatedSystems = [ "aarch64-linux" ]` so it can build and test the aarch packages. This might be a good idea after all so users can cross-compile their overlay or user defined packages.

2021-03-14 23:33 UTC, Pacman99 commented on hosts/default.nix
> +    inherit suites multiPkgs;
Yeah that makes sense. A cross compiling section to the docs would be useful to document what you said.
And there's no harm in including it as a specialArg.

2021-03-15 00:07 UTC, blaggacao commented on lib/default.nix
> -args@{ nixos, pkgs, ... }:
Well, there is [`pkgs-lib`](https://github.com/NixOS/nixpkgs/tree/master/pkgs/pkgs-lib) -- which is `lib` dependent on `pkgs`. And actually `build-support` would have been more accurately re-named as `pkgs-lib/build-support`, I guess, if it wasn't for historical reasons.

Concrete: I'd want to make a library function that is not pure nix, but uses any other scripting language.

I was thinking that I probably _could_ instatiate nixos and get access to `pkgs`  but that would be a different `pkgs` than the rest of this repository.

2021-03-15 00:20 UTC, Pacman99 commented on lib/default.nix
> -args@{ nixos, pkgs, ... }:
I see your point and I like the idea of library functions written in other languages. 
But I would argue that the lib folder in devos root, should just be pure nix functions that are used across devos just like nixpkgs's lib. 
And for other scripts or library functions using other languages belong as an overlay or in pkgs/. As they need to be derivations.
The reason I brought this up, is if lib gets an instance of pkgs, it would always get x86_linux and that would break full multi-arch.

2021-03-15 00:23 UTC, Pacman99 commented on lib/default.nix
> -args@{ nixos, pkgs, ... }:
And following what you said, perhaps you could add a pkgs-lib to the pkgs folder. That would would get multi-arch support too.

2021-03-15 00:24 UTC, blaggacao commented on lib/default.nix
> -args@{ nixos, pkgs, ... }:
@Pacman99 You're absolutely spot on with your reply / analysis. Let's drop this then and I'll refactor the docs and adapt my use case.

2021-03-15 00:26 UTC, blaggacao commented on lib/default.nix
> -args@{ nixos, pkgs, ... }:
https://github.com/divnix/devos/issues/166

2021-03-15 00:33 UTC, Pacman99 commented on hosts/NixOS-a64.nix
> +  nixpkgs.system = "aarch64-linux";
Yeah a test would be a good idea, I'll try to add one. 
But we still need to communicate to users that devos will respect nixpkgs.system without them having to dig through hosts/default.nix.

2021-03-15 00:41 UTC, Pacman99 commented on hosts/README.md
> +that architecture. The definition must be one exported by the nixpkgs flake.
Does this sound ok?

2021-03-15 00:49 UTC, Pacman99 commented on hosts/NixOS-a64.nix
> +  nixpkgs.system = "aarch64-linux";
Will `nix flake check` fail if the tests you wrote were exported to all architectures? I was thinking of moving the checks output to under `systemOutputs` so the tests also have multi-arch support. I'm also trying to reduce the use of the one instantiated x86_64 pkgs above nixosConfigurations.

2021-03-15 00:50 UTC, Pacman99 commented on hosts/NixOS-a64.nix
> +  nixpkgs.system = "aarch64-linux";
well I guess my question is if `nix flake check` tries to go through the checks for all architectures.

2021-03-15 01:04 UTC, Pacman99 commented on hosts/NixOS-a64.nix
> +  nixpkgs.system = "aarch64-linux";
yup just tested it, looks like it does

2021-03-15 01:15 UTC, blaggacao commented on hosts/README.md
> +that architecture. The definition must be one exported by the nixpkgs flake.
```suggestion
Set `nixpkgs.system` to the architecture of this host. Keep in mind 
that mostly not all packages are available for all architectures.
```

2021-03-15 01:21 UTC, Pacman99 commented on hosts/README.md
> +that architecture. The definition must be one exported by the nixpkgs flake.
Yeah I like that better.

2021-03-15 02:16 UTC, Pacman99 commented on flake.nix
> +              lib = nixos.lib // { dev = lib; };
Not sure this is the best way to do this.

2021-03-15 02:18 UTC, blaggacao commented on flake.nix
> +              lib = nixos.lib // { dev = lib; };
Have you seen this: https://github.com/divnix/devos/blob/d7f15a664d20de910611a29167107aee8ff0dbab/lib/devos/mkPkgs.nix#L53-L58

?

2021-03-15 02:18 UTC, Pacman99 commented on flake.nix
> +              deployChecks = deploy.lib.${system}.deployChecks { nodes = deployHosts; };
This isn't currently working. For some reason `nix flake check` evaluates all systems starting with 'x86_64'. Including x86_64-darwin, which now fails because the related nixpkgs doesn't evaluate on x86_64-linux.

Any ideas on what to do for this @nrdxp?

2021-03-15 02:21 UTC, Pacman99 commented on flake.nix
> +              lib = nixos.lib // { dev = lib; };
Yeah thats what is currently being used. But I'm trying to avoid instantiating a nixpkgs for x86_64, just for pure nix lib functions.

2021-03-15 02:27 UTC, blaggacao commented on flake.nix
> +              lib = nixos.lib // { dev = lib; };
Maybe you could adopt it here:
```nix
 lib = nixos.lib.extend (lfinal: lprev: { 
   dev = self.lib;
   utils = inputs.utils.lib; 
 }); 
```

2021-03-15 16:00 UTC, Pacman99 commented
Also switched to _module.args here, I think thats more correct.

2021-03-16 03:55 UTC, Pacman99 commented
dropped multiPkgs as a module arg in favor of #164. This is a rare use case anyways, and self.packages can be used instead.

2021-03-16 04:26 UTC, Pacman99 commented on flake.nix
> +              deployChecks = deploy.lib.${system}.deployChecks { nodes = deployHosts; };
I'm trying to debug this and I can't understand why nix flake check evaluates x86_64-darwin checks. I would assume that it would only build the checks for the current system.

2021-03-16 04:30 UTC, Pacman99 commented on flake.nix
> +              deployChecks = deploy.lib.${system}.deployChecks { nodes = deployHosts; };
Ohh I see it tries to evaluate all systems which normally shouldn't be an issue, but because of the patched-nixpkgs it ends up using IFD. This is a known issue nixos/nix#4265.

2021-03-17 00:38 UTC, Pacman99 commented
Fixed merge conflicts in latest push

2021-03-17 01:02 UTC, blaggacao commented
> And following what you said, perhaps you could add a pkgs-lib to the pkgs folder. That would would get multi-arch support too.

While starting to work on #166, would it be possible to create a folder `./lib/pkgs-lib` that _does_ depend on packages, but still lives within the `./lib` folder.

The reason is that I think `./lib` token face value interpretation should still prime over `./lib` as a dependency root, which to the average user is a little more subtle concept.

Hence the average user wold certainly wonder why a library function (regardless of it's dependencies) does not reside in a top level folder that is called precisely `lib`rary.

It's just an UX thing, but I think `devos` cares.

2021-03-17 01:09 UTC, Pacman99 commented
I'm still against passing pkgs to lib/default.nix. It is consistent to use pkgs/pkgs-lib with the way nixpkgs does it so I don't see how it would be surprising or bad UX.

If the lib/pkgs-lib folder is imported in a seperate line in flake.nix thats ok. The issue right now is `lib` is not a multi arch output, because it should just be pure nix functions. So any function written with the pkgs passed to lib will only run on one architecture..

2021-03-17 01:18 UTC, blaggacao commented
> If the lib/pkgs-lib folder is imported in a seperate line in flake.nix thats ok.

That would have been my idea. I don't feel the nixpkgs's own top level dichotomy is particularly lucky. `./pkgs` is such a hodgepodge of all sorts of things. That makes it actually harder for beginners to cut through. It would be nice if we could rather git `./pkgs` a razor sharp mental profile.

> The issue right now is lib is not a multi arch output, because it should just be pure nix functions. So any function written with the pkgs passed to lib will only run on one architecture..

I'm goging to anticipate this for #166

2021-03-17 01:23 UTC, Pacman99 commented
That is a good point, but I still think proper multi arch support is more important. Is it alright if I still remove it in this PR, since theres no function atm that needs it. And we can figure out how to reintegrate it properly when we need it.

2021-03-17 01:36 UTC, blaggacao commented
Perfect!

2021-03-17 02:00 UTC, nrdxp commented
> That is a good point, but I still think proper multi arch support is more important. Is it alright if I still remove it in this PR, since theres no function atm that needs it. And we can figure out how to reintegrate it properly when we need it.

Whe it's ready feel ready.

bors delegate+

2021-03-17 02:02 UTC, Pacman99 commented
This will fail right now because of multi arch checks. So its blocked by #192.

2021-03-17 02:22 UTC, Pacman99 commented on hosts/NixOS-a64.nix
> +  nixpkgs.system = "aarch64-linux";
Dropped nixos-a64.nix. I'm not sure how to write a test specifically for multi arch. I might try to figure it out later, but I don't think its completely necessary. And mulltiarch checks helps too.

2021-03-19 01:45 UTC, Pacman99 commented
I updated this PR so its no longer blocked by #192. Until we have proper multi-arch tests, the tests are now only imported if the system is x86_64-linux.

2021-03-19 07:17 UTC, nrdxp commented
Been out all day. Super exhausted, but I'll have a proper review of this tomorrow. Good job.

2021-03-19 18:51 UTC, nrdxp requested changes
This is all but ready. Just fix my small nitpick in the docs and we can go ahead and merge it.

2021-03-19 18:51 UTC, nrdxp commented on hosts/README.md
> +Set `nixpkgs.system` to the architecture of this host, default is "x86_64-linux".
I would make this a note. As the continuation from the previous paragraph doesn't really flow well. Plus, we want it to stand out so users don't overlook this information.

so Just
> ##### _Note_:
> Set `nixpkgs.system` to the architecture of this host, default is "x86_64-linux". ...

Other than that. I think this is ready

2021-03-19 18:55 UTC, Pacman99 commented on hosts/README.md
> +Set `nixpkgs.system` to the architecture of this host, default is "x86_64-linux".
Good idea, that looks better. Can you look at the update. I followed the format of notes from the docs folder.

2021-03-19 19:01 UTC, nrdxp commented on hosts/README.md
> +Set `nixpkgs.system` to the architecture of this host, default is "x86_64-linux".
Almost there. The format I've used throughout the docs so far includes blockquotes and a level 5 header.

```markdown
> ##### _Note:_
> Some cool note.
```
or for multiple notes:

```markdown
> ##### _Notes:_
> * A note
> * Another note
```

2021-03-19 19:07 UTC, Pacman99 commented on hosts/README.md
> +Set `nixpkgs.system` to the architecture of this host, default is "x86_64-linux".
Ok got it, should be fixed now

2021-03-19 19:24 UTC, Pacman99 commented on hosts/README.md
> +Set `nixpkgs.system` to the architecture of this host, default is "x86_64-linux".
Missed the blockquotes. I think its good now.

2021-03-19 19:33 UTC, nrdxp approved these changes
Good to go.

bors r+

2021-03-19 19:54 UTC, merged