iso: only include the host's dependencies
divnix/devos pull request #197
Opened 2021-03-17 17:49 UTC by Pacman99

fixes #194 

I've only tested that the iso build evaluates. I still have to test that it builds. And this change *could* break the current iso build, so it definitely has to be tested thoroughly. 

I came up with a pretty simple solution though, so I thought I may as well share it. Instead of importing all modules, I just added the hosts toplevel into the iso's storeContents.

cc @blaggacao

2021-03-17 20:26 UTC, nrdxp commented
This looks great! 

I was wanting to devise a way to actually test the iso as part of CI, but building the actual iso image itself is quite expensive both in space and time. Not sure if there would be any other way to reliably test it on each change though without having to build and squash the image.

If we can come up with something, perhaps we can include it in this PR.

2021-03-17 22:06 UTC, blaggacao commented
This is _really_ elegant, but at least we would need the (basic) user profiles so that remote access still works. Maybe re-importing the [base suite](https://github.com/divnix/devos/blob/core/suites/default.nix#L18) suffices. Basically replicate how it is done [here](https://github.com/divnix/devos/blob/bf9749b98a4a22135abc4cad525f81f42f597b0f/hosts/NixOS.nix#L4). That would solve this problem and not break the docs (though complementing them is necessary).

2021-03-17 22:21 UTC, Pacman99 commented
> I was wanting to devise a way to actually test the iso as part of CI, but building the actual iso image itself is quite expensive both in space and time. Not sure if there would be any other way to reliably test it on each change though without having to build and squash the image.

I would like to see that too. But it does take a while to build the iso. Perhaps if we could just import the iso modules into the test node and inspect different parts of the machine once started up.

> Maybe re-importing the base suite suffices. Basically replicate how it is done here. That would solve this problem and not break the docs (though complementing them is necessary).

I didn't even think of that! Yeah I knew this would break things, thanks for figuring what exactly it broke :) 
So I tried adding the base suite, but then that runs into the problem of home-manager missing. I think getting that to work will require a rework of `hosts/default.nix` and `devosSystem`. We might want to consider not passing ALL the modules as one list and instead seperating them. Or passing them as an attrset, so different parts of devosSystem can pick apart the necessary modules. And then a final `attrValues` of the attrset could be used in the final host.

2021-03-17 22:54 UTC, Pacman99 commented
With #198, I can selectively import the base suite and flakeModules - which contains home-manager. Since those are the only two that declare new options(I think!), I think that should get any user's base suite to evaluate.

2021-03-18 00:43 UTC, blaggacao commented
I think `core` is valuable too for the unified "sysadmin experience".

2021-03-18 00:46 UTC, Pacman99 commented
Yeah I'm actually thinking now of just including everything but local and lib.

2021-03-18 00:54 UTC, blaggacao commented
That is a good idea, the environments should be probably as close as possible in every aspect, just not starting more systemd services than declared in `suites.base` and `profiles/core`.

I have a hard time following up on the home-mamager problwm you reported. What is it about?

2021-03-18 01:01 UTC, Pacman99 commented
> That is a good idea, the environments should be probably as close as possible in every aspect, just not starting more systemd services than declared in suites.base and profiles/core.

I add a change to forward environment.systemPackages. But either way every other dependency is in the store, they just have to be installed to the profile.

> I have a hard time following up on the home-mamager problwm you reported. What is it about?

So the base suite imports the users which set the home-manager options. But without importing extern, those options don't exist, so the evaluation fails. And it indicates a general problem with trying to import parts of the host's config without the necessary modules. If a user had declared options in a custom module, then importing the base suite would then fail.

2021-03-18 01:06 UTC, blaggacao commented
Ok, I understand. So we need to make sure to actually import all _modules_ but only core, nixos-user and root-user profiles. Right?

2021-03-18 01:12 UTC, blaggacao commented
For a live installer we actually only need core + root. We can drop nixos. We should actually drop nixos, since deploy-rs does require _passwordless_ sudo and it's quite easy to set a password for `nixos` during install (you are prompted).

2021-03-18 03:16 UTC, Pacman99 commented
Filtering out users is a good idea, but does the root user have ssh access to the iso by default? So if I understand right, the user adds an ssh public key to the root user module which is imported to the iso build. And then you can now ssh into the system as the root user.  But we don't want to include the other users as that would be unnecessary and will likely have a password.

So instead of importing the base suite, I'm now just importing `suites.allUsers.root`.

2021-03-18 04:08 UTC, nrdxp commented
I have occasion to test this out as it looks like I fudged my zfs ashift settings and need to recreate my pool. I'll report back how it goes.

2021-03-18 04:42 UTC, Pacman99 commented
Updated to include core, global, flakeModules, and modOverrides. The last two aren't really necessary, but they will prevent an evaluation failure in the rare case someone uses home-manager or sets some other option expecting an overridden module

2021-03-18 04:44 UTC, blaggacao commented
> but does the root user have ssh access to the iso by default?

No, but it is documented how to do that. Wording might be in need of alight tweaking after this discussion.

2021-03-18 04:46 UTC, nrdxp commented on lib/devos/devosSystem.nix
> +      hostConfig = (lib.nixosSystem args).config;
This needs to be `hostConfig = (lib.nixosSystem (args // { modules = moduleList; })).config` due to modules being a set now.

2021-03-18 04:48 UTC, blaggacao commented
> Updated to include core, global, flakeModules, and modOverrides.

I think this is actually necesarry (and all other _modules_, too) in order to be robust.

This is why I would rather invert the logic woth a selector:

- everytjing
- less all suites.allProfiles - except `core`
- less all suites.allUsers - except `root`

Such a negative selector is much more robust than a positive one. Actually a positive one is not correct here.

2021-03-18 04:49 UTC, nrdxp commented on lib/devos/devosSystem.nix
> +            hostConfig.lib.specialArgs.suites.allUsers.root
This doesn't work as `allUsers` is actually a list not a set. We can just export users in suites, which we currently don't do, but assuming users haven't modified this may be a bad idea, as I actually deleted this user on my personal config and it caused a failure. Plus the default root user only sets an empty root password anyway, which I think the ISO config already does.

2021-03-18 04:53 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +            hostConfig.lib.specialArgs.suites.allUsers.root
I think, at least for now, I'm just going to import the base suite. So that way all users are imported and it gives the ability for users to configure whats included in the iso.

2021-03-18 04:54 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +            hostConfig.lib.specialArgs.suites.allUsers.root
I think the main goal here is to allow users to set their ssh public key.

2021-03-18 04:55 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +      hostConfig = (lib.nixosSystem args).config;
fixed

2021-03-18 04:59 UTC, blaggacao commented on lib/devos/devosSystem.nix
> +            modules.global
How does future self know that it needs to add lines here if it modifies hosts/default.nix adding more modules?

2021-03-18 05:00 UTC, blaggacao requested changes
This is the reason for why I'm more in favor of anegative selector ...

2021-03-18 05:01 UTC, Pacman99 commented
@blaggacao I'm not entirely sure what you mean? Isn't the goal here to only import the necessary things as to prevent unecessary system startup while still copying the closure. And with that in mind I would think a positive selector is better. So in the future if more modules get added, we have to go through and evaluate if they should be in the isoConfig.

Could you perhaps share a nix expression as to what should be imported. I think might clear up confusion.

2021-03-18 05:03 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +            modules.global
I feel like thats a good thing, that we have to evaluate the importance of modules added to hosts/default.nix before adding them to isoConfig.

2021-03-18 05:03 UTC, nrdxp commented
If we really wanted to go deep. We could pass args to each module manually, and then, if the module happens to define a systemd service, we can filter it out of it's config session before including it. Might be more complex than it sounds though.

2021-03-18 05:04 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +            modules.global
>Future self can silently break things beyond the reach of the hosts/default.nix scope.

I think theres potential to break things either way. moving the discussion for positive vs. negative selector here.

2021-03-18 05:10 UTC, blaggacao commented
The goal can be reached in two ways, indeed.

Per #194 we want ro avoid systemd to start up. If I recall the docs correctly, those type of things are _only_ defined in profiles. That might be user profiles (in theory: user systemd serbices) or regular profiles.

No systemd serbice is ever avtivated by a _module_ (maybe specified, etc. But not switched on).

But modules define options that a profile (which we need here) might use. We just don't know if and which one.

Hence, we need to include _all_ modules, but no profile, except the ones we clearly document,so that users will know, that if they put a systemd service in one of those profiles, it will start as part of the live installer.

I suggest, we only document `core` and `root`. (And if there is no root, nothing bad happens, you just can't ssh into the live installer, where the only user you really need is root).

2021-03-18 05:18 UTC, blaggacao commented
So the logic would be: +-

`modulesList - suites.allProfiles - suites.allUsers + core + root`

2021-03-18 05:25 UTC, blaggacao commented
If beeing able to ssh into root is unwanted, we can also choose nixos insstead. I think that might be a concern, indeed. We just would need to make sure that for `deploy-rs` this user has _passwordless_ sudo. But maybe that can actually be considered an issue in upstream deploy-rs.

So let's rather use `nixos` and file an issue in deploy-rs.

2021-03-18 05:25 UTC, Pacman99 commented
Okay I think I clearly follow what your saying and I agree. I just pushed a commit that I believe accomplishes it. Its all modules except local and lib. Which is essentially `modulesList - allProfiles`. And as I said earlier, I'm just importing the entire base suite. I don't know how to filter out users, and also I don't see a point in doing so. User services are usually really light if any are even defined. And it could be nice to login to your user and get an environment your comfortable with.

2021-03-18 05:26 UTC, blaggacao commented
Agreed! I'll file an issue in deploy-rs then.

2021-03-18 05:27 UTC, Pacman99 commented
I think there is an issue in deploy-rs for password based sudo. Unless I misunderstand and your talking about something else.

2021-03-18 05:36 UTC, blaggacao commented
This is starting to look pretty clean. i can test tomorrow on my setup end to emd manually for a final round pf feedback / approval. 👍

2021-03-18 05:44 UTC, nrdxp commented
> I'm in an excellent position to try this out since I'm deploying a cage kiosk service, and before this PR I would have to manually build with cage switched to opening a terminal instead of a browser.

After testing tomorrow, if you could compile what you learn about bootstrapping and write a nixos integration test for the iso config, that would be amazing. I especially want to test the link local stuff to ensure it's actually working as we move forward.

2021-03-18 12:47 UTC, blaggacao commented on lib/devos/devosSystem.nix
>                  self.devShell.${config.nixpkgs.system}
We should be able to add `drvPath` for devshell, as well, fixing #195, shall we?

Not meaning to block this PR, though.

2021-03-18 17:17 UTC, blaggacao commented on lib/devos/devosSystem.nix
>                  self.devShell.${config.nixpkgs.system}
x-ref: https://github.com/Pacman99/devos/pull/2 (also going to test that)

2021-03-18 17:24 UTC, Pacman99 commented on lib/devos/devosSystem.nix
>                  self.devShell.${config.nixpkgs.system}
good idea, merged!, But will that really cache evaluations? I thought evaluation caches were sqlite databases in your home directory. I remember it being a series of sqlite db's with hashe's as names

2021-03-18 17:50 UTC, nrdxp commented on lib/devos/devosSystem.nix
>                  self.devShell.${config.nixpkgs.system}
I believe @Pacman99 is right about the evaluation cache. I've been struggling with how to clear the dang thing for a while now. Pretty annoying when the error message for a failed derivation just becomes the generic:
```console
failure of cached attribute
```
I know I found it's exact location once in order to clear it, but now I can't seem to find it. If it is still in the home dir, perhaps we could make some clever use of home-manager to include it.

2021-03-18 17:52 UTC, Pacman99 commented on lib/devos/devosSystem.nix
>                  self.devShell.${config.nixpkgs.system}
Ohh for me its in `~/.cache/nix/eval-cache-v2`

2021-03-18 17:53 UTC, Pacman99 commented on lib/devos/devosSystem.nix
>                  self.devShell.${config.nixpkgs.system}
you should be able to safely delete that since its just evaluations that can be done again

2021-03-18 17:56 UTC, Pacman99 commented
Just force pushed with a cleanup of the git history. Its just three commits now.

bors try

2021-03-18 19:34 UTC, blaggacao commented
It looks like [this](https://github.com/NixOS/nixpkgs/blob/80c7312da684a0713464313a744486b3b8d66587/nixos/modules/installer/cd-dvd/iso-image.nix#L427-L438) is now taking _forever_. I'll try with `zstd`, but I suspect we rather need to generate an overlay fs (if possible) and store those additional closures (not necessary at boot) just plainly on the files system, without compression and without inclusion into the squashfs.

2021-03-18 19:36 UTC, blaggacao commented
bors try-

2021-03-18 19:44 UTC, blaggacao requested changes
I'll make another try re-adding `local`. Maybe we can later think about tearing local into smaller pieces in search of a concise interface. This breaks image naming...

2021-03-18 19:44 UTC, blaggacao commented on lib/devos/devosSystem.nix
> +      isoModules = (builtins.attrValues (builtins.removeAttrs modules [ "local" "lib" ]));
Result of my tests: removing `local` removes the correct hostname. The result is a badly named iso image:

`result/iso/nixos-nixos-20.09.20210312.60b18a0-x86_64-linux.iso` instead of

`result/iso/nixos-POS-20.09.20210312.60b18a0-x86_64-linux.iso`

2021-03-18 19:45 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +      isoModules = (builtins.attrValues (builtins.removeAttrs modules [ "local" "lib" ]));
I can pass hostName manually

2021-03-18 20:09 UTC, blaggacao commented
I think we should revert to strictly solve #194 and leave the other stuff for another PR. It is too hard to isolate and understand cause-effects relationship with mixed concerns if every end-to-end test takes more than 2 hours.

2021-03-18 21:53 UTC, Pacman99 commented
> I think we should revert to strictly solve #194 and leave the other stuff for another PR.

Isn't that the entire point of all the changes in this PR? I'm confused as to what you would like to revert to. Either we import all modules or figure out a way to include the closure and import necessary modules. This PR is trying to do the latter.

> It is too hard to isolate and understand cause-effects relationship with mixed concerns if every end-to-end test takes more than 2 hours.

I think its ok if we take some time to figure out this PR. Also another way to test could be to build the isoConfig's toplevel and inspect the files in there.

2021-03-18 22:48 UTC, blaggacao commented
I'm gonging to test now alternative implementation https://github.com/divnix/devos/pull/202 which tries not to introduce side effects. It still includes https://github.com/divnix/devos/pull/202/commits/2bd331429d7a89f0f94aeaf36fff6195f25cd240 as we already started to go down that road with https://github.com/divnix/devos/pull/198 although its not strictly necessary for solving #194

2021-03-18 23:19 UTC, Pacman99 commented
Borrowed @blaggacao's idea of using disabledModules here. And I think this should avoid potential side effects.

2021-03-19 00:24 UTC, blaggacao commented on lib/devos/devosSystem.nix
> +              environment.systemPackages = hostConfig.environment.systemPackages;
What was the rationale (use case) for this again?

2021-03-19 00:26 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +              environment.systemPackages = hostConfig.environment.systemPackages;
Well by including the hostConfig toplevel, all packages are now in the nix store. So I thought as  convenience we could just forward to the environment.

2021-03-19 00:29 UTC, blaggacao commented
I get a segfault on its current state, maybe the `lib.remove` doesn't work as intended?  #202 builds now an I could start into the live installer, going to rebase my cage project on #202 to finally verify #194.
```
/nix/store/vf2f1xph3v6afy0bx0cf46bp82qincpy-devshell-dir/bin/flk: line 28: 308429 Segmentation fault      (core dumped) nix build "$DEVSHELL_ROOT#nixosConfigurations.$2.config.system.build.iso" "${@:3}
```

2021-03-19 00:35 UTC, Pacman99 commented
`nix build .#nixosConfigurations.NixOS.config.system.build.iso` works for me Not sure where the segfault comes from. But that seems like a nix issue.

2021-03-19 00:40 UTC, blaggacao commented on lib/devos/devosSystem.nix
> +              environment.systemPackages = hostConfig.environment.systemPackages;
I'm actually not sure if we can include the toplevel derivation, it takes a lot more time to produce the squashfs, now. Well, maybe we can leave it, but open an issue in search for a better solution (eg. wo compression?).

So we might just leave this line, as well.

2021-03-19 01:27 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +              environment.systemPackages = hostConfig.environment.systemPackages;
I'm currently attempting to build and I see what you mean. If this PR increases the time to build or the iso size by a lot, it might not be the best solution.

Perhaps we could just forward the systemPackages and not include the toplevel build. Or we could add a separate build that has the entire toplevel. So one for network install and one that includes everything making an offline install possible.

2021-03-19 03:56 UTC, blaggacao commented on lib/devos/devosSystem.nix
> +                hostConfig.system.build.toplevel
It looks like this is actually redundant: https://github.com/NixOS/nixpkgs/blob/a6155fc19e31fe0a49b75409d02a2d8b6bb97aa0/nixos/modules/installer/cd-dvd/iso-image.nix#L627-L638

and we need to remove the `*.drvPath`. THose are the size culprits

2021-03-19 03:58 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +                hostConfig.system.build.toplevel
Ohh I see, fixed in latest commit

2021-03-19 03:59 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +                hostConfig.system.build.toplevel
what does includeSystemBuildDependencies mean? I would assume if you pass the toplevel, that would include all buildInputs for that store path.

2021-03-19 04:00 UTC, blaggacao commented
Can you also merge https://github.com/Pacman99/devos/pull/3? So I can try again off of this branch here?

2021-03-19 04:02 UTC, blaggacao commented on lib/devos/devosSystem.nix
> +                hostConfig.system.build.toplevel
You can also remove the `.toplevel`, it's already included as in the linked default config is shown.

> what does includeSystemBuildDependencies mean?

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/iso-image.nix#L482-L486

2021-03-19 04:03 UTC, blaggacao commented
@Pacman99 For various reasons, this has taken me a whole day already, and I still wasn't able to test this fully. Are you ok, if we turn over the page and continue on #202 ? It's just too hard for me to keep track of all those things while not being able to commit here... (sry)

2021-03-19 04:05 UTC, Pacman99 commented on lib/devos/devosSystem.nix
> +                hostConfig.system.build.toplevel
are you talking about this line: https://github.com/NixOS/nixpkgs/blob/a6155fc19e31fe0a49b75409d02a2d8b6bb97aa0/nixos/modules/installer/cd-dvd/iso-image.nix#L630?

That would get the toplevel of the isoConfig. Which won't include the profiles that have been disabled. And the goal is to include the profile's closure, just without including them in the config.

2021-03-19 04:09 UTC, Pacman99 commented
I'll leave this PR open as a draft. But yeah this was mainly meant to demonstrate an idea and I don't think that the idea is viable. I think we'll have to experiment more to get a better overall solution. But I'm not sure #202 is much better since its basically the same as this PR but with a few tweaks.

2021-03-19 04:09 UTC, blaggacao commented on lib/devos/devosSystem.nix
> +                hostConfig.system.build.toplevel
Yep, just realized that my self and renamed to `fullHostConfig` and left a [comment](https://github.com/blaggacao/devos/blob/b9a256605d6b7e77e787c0565b8e42bb7427a1f9/lib/devos/devosSystem.nix#L32-L34). That makes the difference clearer.

2021-03-19 04:10 UTC, Pacman99 commented
Perfectly fine with continuing there though since you're the one doing most of the testing anyways itll be easier for you to update.

2021-03-19 19:40 UTC, Pacman99 commented
I think the CI runner is still trying to evaluate this PR, but I don't think the CI runner is even available right now.

2021-03-22 22:06 UTC, Pacman99 commented
Included in #202

2021-03-22 22:06 UTC, closed without merging