Prevent importing files within lib and shell
divnix/devos pull request #217
Opened 2021-03-26 16:56 UTC by Pacman99

Changes shell and mkPkgs to take extern, overrides, and pkgs as an argument. This improves their ability to be used as lib functions.

2021-03-26 21:35 UTC, nrdxp commented on shell/default.nix
> +, pkgs ? import <nixpkgs> {}
This may not be such a great idea, as there is no guarantee the NIX_PATH is gonna contain a `nixFlakes` version that works with the _flk.sh_ script.

2021-03-26 21:42 UTC, Pacman99 commented on shell/default.nix
> +, pkgs ? import <nixpkgs> {}
Ok I can remove that change, it's pretty unnecessary.

2021-03-26 21:43 UTC, Pacman99 commented on shell/default.nix
> +, pkgs ? import <nixpkgs> {}
removed that change.

2021-03-27 00:22 UTC, nrdxp commented on lib/devos/mkPkgs.nix
> +{ extern, overrides }:
wouldn't this have to come first?

2021-03-27 00:32 UTC, Pacman99 commented on lib/devos/mkPkgs.nix
> +{ extern, overrides }:
Can you elaborate? first as in before what?

2021-03-27 00:34 UTC, nrdxp commented on lib/devos/mkPkgs.nix
> +{ extern, overrides }:
As in the first arguement, before `{ lib, dev, nixos, self, inputs, ... }:`

2021-03-27 00:51 UTC, Pacman99 commented on lib/devos/mkPkgs.nix
> +{ extern, overrides }:
really? that would fail, the first line has to be the lib's dependencies and the second line is the actual function arguments. Not sure if I'm just missing something.

2021-03-27 01:13 UTC, nrdxp commented on lib/devos/mkPkgs.nix
> +{ extern, overrides }:
Oops, looks like I forgot that the first arg is passed automatically during lib creation. My bad.

2021-03-27 14:59 UTC, nrdxp approved these changes
This looks good. Just want to ask if it's all finished before merging.
bors try

2021-03-27 15:14 UTC, nrdxp commented
Ah, BORS failed since you added a second argument to mkPkgs, so the call from _shell/default.nix_ needs to be updated with the new args as well.

2021-03-27 16:19 UTC, Pacman99 commented
Right, now I remember why I added the pkgs there in the first place. Uhh I'm not sure how to do this. 
Shell could manually call extern, but it doesn't have access to the right inputs. Well it does right now, but in the future `self` might not actually refer to devos, which is why I switched mkPkgs to get inputs from lib so it has all of them. The other option is pass extern and overrides to shell as we do to pkgs, but that would break compat.

2021-03-27 16:23 UTC, Pacman99 commented on shell/default.nix
> +  }).${system};
I think this should work. The only issue is If shell is ever called with `nix-shell` then it might not have all the right inputs to pass to extern. We could always try to fix this later, not sure.

2021-03-27 17:04 UTC, nrdxp requested changes
Looks like it's almost ready.

2021-03-27 17:04 UTC, nrdxp commented on flake.nix
> +            inherit self system extern overrides;
overrides is not in scope here, causing an error.

2021-03-27 17:09 UTC, Pacman99 commented on flake.nix
> +            inherit self system extern overrides;
ok right fixed, I think I forgot to run a `nix flake check` before pushing this change.

2021-03-27 17:30 UTC, nrdxp commented on shell/default.nix
> +  }).${system};
`nix-shell` actually works fine in this case, after testing on my end.

2021-03-27 17:31 UTC, nrdxp approved these changes
bors r+

2021-03-27 17:32 UTC, Pacman99 commented on shell/default.nix
> +  }).${system};
It does now I'm more talking about future when mkFlake calls shell. The self that it gets might be the flake thats calling it. And if you notice in the `mkFlake` PR I pass both the current self's inputs and devos's inputs to extern. That won't happen here, so if a user's extern was, for example, referring to deploy-rs, but they didn't include it in their own flake, shell would fail.

2021-03-27 17:33 UTC, merged