Drop flattenTreeSystem and use custom function for filtering packages
divnix/devos pull request #220
Opened 2021-03-26 21:54 UTC by Pacman99

I don't think we should flatten the system because if a user doesn't make a package a derivation in pkgs/default.nix we should trust that there is a reason for doing so. So instead this drops the flattenTreeSystem reference(and switches to flake-utils master branch) and replaces its usage with a custom function `filterPackages`. This function filter all packages that match three conditions;
 - is a derivation
 - not broken
 - system is supported
In that order as to not cause errors when trying to reference derivation meta attributes.

And then also just dump *all* packages into legacy packages, so everything else is still accessible. I was considering removing the packages that are already in the packages output in legacyPackages, but I don't think its necessary since nix looks to the packages output first.

2021-03-26 22:33 UTC, nrdxp requested changes

2021-03-26 22:33 UTC, nrdxp commented on lib/attrs.nix
> +        builtins.elem system v.meta.platforms);
May want to add a let binding to `filter` such as:
```nix
let platforms = meta.hydraPlatforms or meta.platforms or [ ]; in # ...
builtins.elem system platforms
```
Code comes directly from `flattenTreeSystem` itself since some packages define only `hydraPlatforms`, while others define only `platforms`. The empty list ensure evaluation won't fail if neither exist.

2021-03-26 23:34 UTC, Pacman99 commented on lib/attrs.nix
> +        builtins.elem system v.meta.platforms);
just updated with suggestion

2021-03-26 23:54 UTC, nrdxp requested changes
The code changes are good, but for the sake of a prettier git log, the first line of a commit message should be kept under 50 chars, while subsequent lines should remain under 72 chars

2021-03-27 00:04 UTC, Pacman99 commented
> The code changes are good, but for the sake of a prettier git log, the first line of a commit message should be kept under 50 chars, while subsequent lines should remain under 72 chars

fixed! I really should stop using `git commit -m`

2021-03-27 00:10 UTC, nrdxp approved these changes
It's all good. I've made the same mistake. Good work!
bors r+

2021-03-27 00:12 UTC, merged

2021-03-27 15:55 UTC, blaggacao commented
What is this mainly motivated by (for the record)?

Is this motivated by the issues we had with flake checks & multiplatform?

2021-03-27 16:04 UTC, nrdxp commented
some [context](https://github.com/divnix/devos/pull/218#issuecomment-808487785)

Also `flattenTreeSystem` never got merged into flake-utils and was instead closed, so if the branch ever got deleted users might be  pretty upset as well.