feature: Add pkgs fetch manager nvfetcher
divnix/devos pull request #325
Opened 2021-06-14 03:57 UTC by GTrunSec

Regarding motivaion in https://github.com/divnix/devos/issues/299

2021-06-14 04:08 UTC, blaggacao commented on flake.nix
> +              })
```suggestion
            #nvfetcher for sources
            (final: prev: {
              sources = (import ./sources.nix) { inherit (final) fetchurl fetchgit; };
            })
```

2021-06-14 04:09 UTC, blaggacao commented on flake.nix
> +            ]))
Is this necessary for the Jhon Doe user?

2021-06-14 04:10 UTC, blaggacao commented on sources.nix
> +_build/generated.nix
Can we rather generate `sources.nix` directly? It would be better not to introduce a new top level folder.

2021-06-14 04:11 UTC, blaggacao commented on nvfetcher.toml
> +# nvfetcher.toml
Is there a way we can name this file `sources.toml`?

2021-06-14 04:11 UTC, blaggacao commented
Super nice! Will continue tomorrow! :rocket:

2021-06-14 04:11 UTC, GTrunSec commented on flake.nix
> +            ]))
sure, if not how to use the command of `nvfetcher build`

2021-06-14 04:13 UTC, GTrunSec commented on nvfetcher.toml
> +# nvfetcher.toml
sure,  we can use nvfetcher build -c `sources.toml`

2021-06-14 04:13 UTC, GTrunSec commented on sources.nix
> +_build/generated.nix
This file was generated by nvfetcher.

2021-06-14 04:26 UTC, GTrunSec commented on flake.nix
> +              })
Thanks

2021-06-14 04:32 UTC, blaggacao commented on flake.nix
> +            ]))
Oh I had thought the `pkgs.nvchecker` as enough.

2021-06-14 04:34 UTC, blaggacao commented on sources.nix
> +_build/generated.nix
Maybe to provide an extension point for manual stuff. Hmm ...

@berberman can you enlighten us?

2021-06-14 04:38 UTC, blaggacao commented
We also need to make sure `./_build/.shake*` blobs doen't get committed.

2021-06-14 04:51 UTC, berberman commented on sources.nix
> +_build/generated.nix
The feature *extract src* (`extract = [ "file_1", "file_2", ...]`) and *rust support* (`cargo_lock = Cargo.lock`) will extract `file_1`, `file_2`, and `Cargo.lock` to `_build` directory. Extracted files will be referenced by `generated.nix`, and `sources.nix` is a symlink of `_build/generated.nix`. In short, `sources.nix` is no loger the only generated file.

What I have in mind is that we should keep the entire `_build` as the artifact of the build system, but it seems that this is not appropriate in some cases. :thinking:

2021-06-14 05:01 UTC, berberman commented on flake.nix
> +            ]))
I guess we also need `pkgs.nix-prefetch-git` here

2021-06-14 05:09 UTC, berberman commented on flake.nix
> +            ]))
This is for people who want to use Haskell DSL to define their packages and extend `nvfetcher`, like https://github.com/berberman/flakes/blob/master/Update.hs.

We could append the `buildInputs` of [`ghcWithNvfetcher`](https://github.com/berberman/nvfetcher/blob/b6970c017689ba9495d0c8a64b8d464f0a0aca9f/flake.nix#L32-L38) to this list, so that we don't have to duplicate dependencies of `nvfetcher` again.

2021-06-14 13:03 UTC, blaggacao commented on sources.nix
> +_build/generated.nix
Nice feature to start with! :smile:

Can we rather name it `_sources`, then?

2021-06-14 13:05 UTC, blaggacao commented on flake.nix
> +            ]))
I think in this case, we should not place the haskell compiler in the devshell dependencies. Assuming `pkgs.nvfefcher` doesn't have that as a runtime dependency.

2021-06-14 21:39 UTC, GTrunSec commented on flake.nix
> +            ]))
It looks like the `pkgs.nvfecher-bin` enough for us.

2021-06-14 21:43 UTC, GTrunSec commented on sources.nix
> +_build/generated.nix
>Can we rather name it _sources, then?

No, we can't do it here. But this should be a PR in `nvfetcher`

2021-06-14 22:47 UTC, nrdxp commented
What's the deal with the new issue template? And I'd be really great to have some documentation so I can try this out :laughing:

2021-06-15 00:07 UTC, blaggacao commented on pkgs/default.nix
> +  # then, call packages with `final.callPackage`
Would this even work? (iirc, it should)

2021-06-15 00:09 UTC, Pacman99 commented on pkgs/default.nix
> +  # then, call packages with `final.callPackage`
Yes it definitely should

2021-06-15 00:13 UTC, Pacman99 commented on pkgs/default.nix
> +  # then, call packages with `final.callPackage`
but to use sources in a package, you would probably have to do `final.callPackage`

2021-06-15 00:14 UTC, blaggacao commented
Pure cosmetics: https://github.com/berberman/nvfetcher/pull/8

2021-06-15 00:16 UTC, blaggacao commented
@berberman Should the shake binary blobs be commited? or is that more like "I'd keep my local track record and that's fine"?

2021-06-15 00:20 UTC, blaggacao commented on flake.nix
> +            ]))
I think [we should be just fine with nvfetcher-bin](https://github.com/berberman/nvfetcher/blob/b6970c017689ba9495d0c8a64b8d464f0a0aca9f/flake.nix#L53)

2021-06-15 00:49 UTC, blaggacao commented on pkgs/default.nix
> +  # then, call packages with `final.callPackage`
I can confirm this works.

2021-06-15 00:50 UTC, blaggacao commented on overlays/manix.nix
> +    inherit (prev.sources.manix) pname version src;
using `prev` fails until https://github.com/divnix/digga/commit/cfaad0492cc304d408ab0b4899894623ac363e7a is incorporated. Let's not workaround here. The current code is formally correct.

2021-06-15 01:44 UTC, blaggacao commented on flake.nix
> +            ./pkgs/default.nix
fixed by https://github.com/divnix/digga/pull/57

&rarr; `./pkgs`

2021-06-15 02:01 UTC, berberman commented
> @berberman Should the shake binary blobs be commited? or is that more like "I'd keep my local track record and that's fine"?

It's a persistent state of our build system, which caches some results and helps us produce version changelog. It's fine to keep it locally if we don't need to run `nvfetcher` in CI or other places.

2021-06-16 17:32 UTC, Pacman99 commented on pkgs/sources.nix
> +_sources/generated.nix
What is the point of this file? why not just do `prev.callPackage ./_sources/generated.nix`?
The less files added the better.

2021-06-16 17:33 UTC, Pacman99 approved these changes
I like this change a lot, thank you for it!

2021-06-16 21:40 UTC, GTrunSec commented on flake.nix
> +            ]))
>We could append the buildInputs of ghcWithNvfetcher to this list, so that we don't have to duplicate dependencies of nvfetcher again.

you are right.

@blaggacao  Sorry,  the nvchecker and nix-prefetch-git are both needed. So `append the buildInputs` would be a solution here.

2021-06-16 21:53 UTC, blaggacao commented on pkgs/sources.nix
> +_sources/generated.nix
We can't do anything about it it's auto-generated.

2021-06-16 21:55 UTC, Pacman99 commented on pkgs/sources.nix
> +_sources/generated.nix
`sources.nix` is auto-generated? I thought just _sources/generated.nix was.

2021-06-16 22:07 UTC, blaggacao commented on pkgs/sources.nix
> +_sources/generated.nix
Yep

2021-06-16 22:09 UTC, blaggacao commented
I'll squash this and open another PR, before w can merge we need to bump digga and incorporate the overlays order fix.

2021-06-16 22:10 UTC, Pacman99 commented on pkgs/sources.nix
> +_sources/generated.nix
thats a little confusing, since its just a symlink. Would be nice to drop it.

2021-06-16 22:26 UTC, blaggacao commented
Superseded by https://github.com/divnix/devos/pull/328

2021-06-16 22:50 UTC, nrdxp commented
Seems usage is pretty straightforward, but at least a link to the nvfetcher readme would be useful so users are left wondering

2021-06-16 22:50 UTC, Pacman99 commented
@GTrunSec Just letting you know we updated some functionality and squashed the commits to your branch with a force-push.

2021-06-16 22:51 UTC, GTrunSec commented
Ok, Just do it.

2021-06-16 23:09 UTC, blaggacao commented
@Pacman99 Can you add the docs commit?

2021-06-16 23:11 UTC, blaggacao requested changes
Docs, just to make sure we don't accidentally merge this...

2021-06-16 23:12 UTC, blaggacao approved these changes
Thanks! :+1:

2021-06-16 23:13 UTC, Pacman99 commented
We can send a another commit later to use digga develop once the nixos-generators issues get fixed

2021-06-16 23:26 UTC, berberman commented on pkgs/sources.nix
> +_sources/generated.nix
Currently the `--no-output` option can disable generating this symlink.

2021-06-17 15:53 UTC, Pacman99 approved these changes
@GTrunSec Can you look over the changes and merge if your ok with them(with bors r+)
bors delegate+

2021-06-17 17:50 UTC, GTrunSec commented
I got an error output from `nix-shell` with `flake-cmpat` on the latest rev. May you confirm it? Thanks. I guess the problem at here https://github.com/divnix/digga/commit/63538baedbd8bb1fd09687bd1a46eab913a4223b

```
      at /nix/store/p8wl2fqkn99rjmgybgqy4bmjjkw7apy6-source/src/mkFlake/default.nix:85:23:

           84|
           85|     devshellModules = lib.exporters.modulesFromList {
             |                       ^
```

2021-06-17 18:04 UTC, GTrunSec commented
bors r+

2021-06-17 19:16 UTC, blaggacao commented
Oh, thnaks! [`develop` has the fixup](https://github.com/divnix/digga/commit/88f0431746859f09e4b4db4fafb4e9b57ed7e23c)

2021-06-17 20:10 UTC, GTrunSec commented
Now, We can commit some change to develop digga for flake check passing.
bors delegate+

2021-06-17 20:17 UTC, GTrunSec commented
bors r+

2021-06-18 23:40 UTC, GTrunSec commented on flake.nix
> +              nvfetcher-bin = nvfetcher-flake.defaultPackage.${final.system};
I got an issue with `nvfecther-flake.overlay`

```
 attribute 'nvfetcher' missing

       at /nix/store/hf8zm40wwi03wwmjd88djhzhkw49qqbn-source/flake.nix:60:47:

           59|           nvfetcher-bin = with final;
           60|             haskell.lib.justStaticExecutables haskellPackages.nvfetcher;
             |                                               ^
```

2021-06-18 23:44 UTC, GTrunSec commented on flake.nix
> +          imports = [ (digga.lib.importers.modules ./modules) ];
Broken target:
```
attempt to call something which is not a function but a list                                                      
                                                                                                                         
       at /nix/store/f2wp2m962hvb620vmz5yc6fi794ijqz6-source/lib/modulesFromList.nix:39:17:                              
                                                                                                                         
           38|       hasFileAttr = o: builtins.hasAttr "_file" o;                                                        
           39|       peek = f: f (builtins.functionArgs f);                                                              
             |                 ^                                                                                         
           40|                                       
```

2021-06-19 01:38 UTC, blaggacao commented on flake.nix
> +          imports = [ (digga.lib.importers.modules ./modules) ];
Thanks! I'll klean my mess up tomorrow. 😀

2021-06-19 16:37 UTC, Pacman99 commented on pkgs/default.nix
> +  nvfetcher-bin = inputs.nvfetcher-flake.defaultPackage.${final.system};
Lets not pass `inputs` to files, thats what `overlays` is for, can we instead just add an overlay that adds, nvfetcher's defaultPackage

2021-06-19 16:38 UTC, Pacman99 commented on flake.nix
> +      nvfetcher-flake.url = "github:berberman/nvfetcher";
Also can this just be `nvfetcher`, we haven't added `-flake` to any other input

2021-06-19 16:39 UTC, Pacman99 commented on pkgs/default.nix
> +  nvfetcher-bin = inputs.nvfetcher-flake.defaultPackage.${final.system};
```nix
overlays = [
  (final: prev: { nvfetcher = nvfetcher.defaultPackage.x86_64-llinux; })
];
```
in flake.nix

2021-06-19 16:40 UTC, Pacman99 commented on flake.nix
> +              nvfetcher-bin = nvfetcher-flake.defaultPackage.${final.system};
I noticed this error, it seems like it might be a problem in upstream

2021-06-19 18:01 UTC, blaggacao commented
I guess we should bump digga independently of this PR.

2021-06-19 18:33 UTC, GTrunSec commented on pkgs/default.nix
> +  nvfetcher-bin = inputs.nvfetcher-flake.defaultPackage.${final.system};
thanks.

2021-06-19 18:35 UTC, GTrunSec commented
>I guess we should bump digga independently of this PR.

agree with that.

2021-06-19 22:37 UTC, GTrunSec commented on flake.nix
> +            command = "cd $DEVSHELL_ROOT/pkgs; ${pkgs.nvfetcher-bin}/bin/nvfetcher -c ./sources.toml --no-output $@; nixpkgs-fmt _sources/";
nixpkgs-fmt _sources/  for cleanup the trailing whitespace

2021-06-19 23:35 UTC, Pacman99 commented
bors try

2021-06-19 23:44 UTC, blaggacao requested changes
Unfortunately upstream is broken, so I'm blocking this until I could resolve it.

2021-06-20 15:55 UTC, nrdxp commented
upstream nixpkgs, or digga?

2021-06-20 20:08 UTC, blaggacao commented
> digga?

https://github.com/divnix/digga/pull/60

I've fixed `fup` in the mean time, where I had implemented `modulesFromList` working with `_file` attrs to short-sightedly. This change then surfaced https://github.com/divnix/digga/pull/60

2021-06-24 16:49 UTC, nrdxp commented
bors try

2021-06-24 16:52 UTC, nrdxp commented
Really would like to get this sucker merged. After both of your above mentioned PR's have been merged above @blaggacao, what's left blocking this? Do we just need to bump digga?

2021-06-24 17:01 UTC, blaggacao commented
@GTrunSec can you preemtively rebase on https://github.com/divnix/devos/pull/329 ? or maybe we can merge it before you read this, whatever comes first...

2021-06-24 17:51 UTC, GTrunSec commented
Yes, we can merge it. Can you do that?

2021-06-25 01:44 UTC, GTrunSec commented
bors try

2021-06-25 02:12 UTC, nrdxp commented
bors r+

2021-06-25 02:14 UTC, nrdxp approved these changes
bors r+

2021-06-25 02:38 UTC, blaggacao approved these changes

2021-06-25 02:38 UTC, blaggacao commented
bors r+

(everything else will be fixup &mdash; if so)

2021-06-25 02:45 UTC, nrdxp commented
:crossed_fingers:

2021-06-25 02:47 UTC, merged