Replace references to `flk` and `core` with `bud` and `master`
divnix/devos pull request #370
Opened 2021-09-18 19:38 UTC by montchr

Fixes #366 

Blocked by #369 — the docs cannot be updated until the docs workflow is running again. The site hasn't been built since last month despite other recent updates to docs on `master`.

2021-09-18 19:42 UTC, montchr commented on .github/workflows/release.yml
> +          ref: master
Double check me on this – `master` might not be the right choice. I blindly renamed any references to the `core` branch.

2021-09-19 12:36 UTC, blaggacao commented on .github/workflows/release.yml
> +          ref: master
This is correct, thanks!

2021-09-19 12:47 UTC, blaggacao requested changes
I left two small fixup suggestion. Otherwise looks excellent!

Thank you gor this unit of work!

2021-09-19 12:47 UTC, blaggacao commented on doc/integrations/deploy.md
> +deploy "bud#hostName" --hostname host.example.com
This was/is not correct.

It would be `deploy ".#hostName"` (assuming the user is at the root of the repo).

2021-09-19 12:47 UTC, blaggacao commented on doc/start/index.md
> +cd bud
`cd devos`

See: https://github.com/divnix/devos/blob/master/bud/get.bash

(defaults to `devos`)

2021-09-20 03:50 UTC, montchr commented on doc/integrations/deploy.md
> +deploy "bud#hostName" --hostname host.example.com
Fixed in a82c828.

Also note that I changed this example to use single quotes since I know the hash character in the `<dir>#<output>` format sometimes may cause shells to interpret the string as needing expansion (related to string replacement, I think?). I've run into this when running `nix build ".#myHost"` in zsh at least.

2021-09-20 13:10 UTC, merged